<a href="https://colab.research.google.com/github/riya174500/Python-Projects/blob/main/Pandas_DataFrames_03_(Riya).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Pandas
by Ryan Orsinger

## Module 3: DataFrames Continued

### Pandas DataFrames Continued - Identifying Missing Values
- Identifying and counting missing values
- Removing rows with missing information
- Dropping columns from a DataFrame

In [ ]:
import pandas as pd

In [ ]:
# Let's generate some data with missing values.
# Real world data often has missing values
df = pd.DataFrame([
    {
        "item": "crackers",
        "serving_size": "4 crackers",
        "calories": 10,
        "fat": "1.1g",
        "sodium": "125mg",
        "price": 2.99,
        "discount": None
    },
    {
        "item": "club soda",
        "serving_size": "8 oz",
        "calories": None,
        "fat": None,
        "sodium": "75mg",
        "price": 2.25,
        "discount": None

    },
    {
        "item": "apple",
        "serving_size": 2,
        "calories": 95,
        "fat": None,
        "sodium": None,
        "price": 1.99,
        "discount": None
    },
    {
        "item": "banana",
        "serving_size": 3,
        "calories": 105,
        "fat": "0.4g",
        "sodium": "1mg",
        "price": None,
        "discount": None
    },
    {
        "item": "spam",
        "serving_size": "1 tin",
        "calories": None,
        "fat": None,
        "sodium": None,
        "price": None,
        "discount": None
    }
])

# Set the index to be the item name
df.set_index("item", inplace=True)
df

          serving_size  calories   fat sodium  price discount
item
crackers    4 crackers      10.0  1.1g  125mg   2.99     None
club soda         8 oz       NaN  None   75mg   2.25     None
apple                2      95.0  None   None   1.99     None
banana               3     105.0  0.4g    1mg    NaN     None
spam             1 tin       NaN  None   None    NaN     None

In [ ]:
# The .info method outputs data types and non-null value count
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, crackers to spam
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   serving_size  5 non-null      object
 1   calories      3 non-null      float64
 2   fat           2 non-null      object
 3   sodium        3 non-null      object
 4   price         3 non-null      float64
 5   discount      0 non-null      object
dtypes: float64(2), object(4)
memory usage: 280.0+ bytes

In [ ]:
# Notice that missing values in a numeric column show as NaN, which means "not a number"
# For more on NaN, see https://en.wikipedia.org/wiki/NaN
df.calories

item
crackers      10.0
club soda      NaN
apple         95.0
banana       105.0
spam           NaN
Name: calories, dtype: float64

In [ ]:
# NaN exists to allow us to do math without getting execution errors
# Many math functions ignore NaNs
df.calories.mean()

np.float64(70.0)

In [ ]:
# By default, .value_counts ignores NaNs, too
df.sodium.value_counts()

sodium
125mg    1
75mg     1
1mg      1
Name: count, dtype: int64

In [ ]:
# Use dropna=False to count missing values
df.sodium.value_counts(dropna=False)

sodium
None     2
125mg    1
75mg     1
1mg      1
Name: count, dtype: int64

In [ ]:
# Notice that missing values in a string/object column show as None
df.fat

item
crackers     1.1g
club soda    None
apple        None
banana       0.4g
spam         None
Name: fat, dtype: object

In [ ]:
# .isna() can operate on a column, returning a boolean series
df.sodium.isna()

item
crackers     False
club soda    False
apple         True
banana       False
spam          True
Name: sodium, dtype: bool

In [ ]:
# .isna() can also operate on the entire dataframe
df.isna()

           serving_size  calories    fat  sodium  price  discount
item
crackers          False     False  False   False  False      True
club soda         False      True   True   False  False      True
apple             False     False   True    True  False      True
banana            False     False  False   False   True      True
spam              False      True   True    True   True      True

In [ ]:
# Counting the number of nulls by column
print("Number of nulls by column")
df.isna().sum()

Number of nulls by column

serving_size    0
calories        2
fat             3
sodium          2
price           2
discount        5
dtype: int64

In [ ]:
print("Proportion of nulls by column")
df.isna().mean()

Proportion of nulls by column

serving_size    0.0
calories        0.4
fat             0.6
sodium          0.4
price           0.4
discount        1.0
dtype: float64

In [ ]:
# Counting the number of nulls by row
# Recall that .sum can run on columns or by row, by row with axis=1
print("Number of nulls by row")
df.isna().sum(axis=1)

Number of nulls by row

item
crackers     1
club soda    3
apple        3
banana       2
spam         5
dtype: int64

In [ ]:
# Proportion of the number of nulls by row
# Recall that .sum can run on columns or by row, by row with axis=1
print("Proportion of nulls by row")
df.isna().mean(axis=1)

Proportion of nulls by row

item
crackers     0.166667
club soda    0.500000
apple        0.500000
banana       0.333333
spam         0.833333
dtype: float64

### Handling Missing Values
- There's no one right answer for all cases.
- "It depends" is a common answer in data science. Context matters.
- Sometimes missing values might mean zero, depending on the context, so we can fill in zero.
- Sometimes, dropping entire rows or columns is appropriate
- Sometimes, filling missing values makes sense to keep the rest of the row or column's data

In [ ]:
# Example of removing null values
# dropna drops every row with a null value
# Since there is missing data in every row, this is quite destructive...
# the default axis argument is axis=0, which means row-wise
df.dropna()

Empty DataFrame
Columns: [serving_size, calories, fat, sodium, price, discount]
Index: []

In [ ]:
# dropna(axis=1) drops all columns with any missing values
# This is also too destructive to be helpful
df.dropna(axis=1)

          serving_size
item
crackers    4 crackers
club soda         8 oz
apple                2
banana               3
spam             1 tin

In [ ]:
# Let's review the dataframe
df

          serving_size  calories   fat sodium  price discount
item
crackers    4 crackers      10.0  1.1g  125mg   2.99     None
club soda         8 oz       NaN  None   75mg   2.25     None
apple                2      95.0  None   None   1.99     None
banana               3     105.0  0.4g    1mg    NaN     None
spam             1 tin       NaN  None   None    NaN     None

In [ ]:
# The discount column is adding no information here, so we can drop it
df.drop(columns="discount", inplace=True)
df

          serving_size  calories   fat sodium  price
item
crackers    4 crackers      10.0  1.1g  125mg   2.99
club soda         8 oz       NaN  None   75mg   2.25
apple                2      95.0  None   None   1.99
banana               3     105.0  0.4g    1mg    NaN
spam             1 tin       NaN  None   None    NaN

In [ ]:
# Reassign the df
# df.drop(index=["spam"], inplace=True) would produce the same result
df = df[df.index != "spam"]
df

          serving_size  calories   fat sodium  price
item
crackers    4 crackers      10.0  1.1g  125mg   2.99
club soda         8 oz       NaN  None   75mg   2.25
apple                2      95.0  None   None   1.99
banana               3     105.0  0.4g    1mg    NaN

## Additional Resources
- [.isnull](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.isnull.html) is an alias for `isna`.
- The [.value_counts](https://pandas.pydata.org/docs/reference/api/pandas.Series.value_counts.html) documentation
- [Pandas .isna documentation](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.isna.html)

## Exercises
- Use `pd.read_csv` to read `"penguins.csv"` into a dataframe variable named `penguins`
- Write the pandas code to count the number of missing values by column
- Write the pandas necessary to get the proportion of missing values by row. Store this to a variable named `percent_missing_by_row`
- Sort the `percent_missing_by_row` series in descending order. How many of the rows are mostly empty?

In [ ]:
# upload dataset file
# Open Files tab
# Select upload
# Choose and open penguins.csv file downloaded in your system.

In [ ]:
# Use `pd.read_csv` to read `"penguins.csv"` into a dataframe variable named `penguins`
penguins = pd.read_csv("penguins.csv")
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [ ]:
# Use .isna to count the number of missing values by column
penguins.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
year                  0
dtype: int64

In [ ]:
# Write the pandas necessary to get the proportion of missing values by row.
# Store this to a variable named `percent_missing_by_row`
percent_missing_by_row = penguins.isna().mean(axis = 1)*100
percent_missing_by_row

0       0.0
1       0.0
2       0.0
3      62.5
4       0.0
       ...
339     0.0
340     0.0
341     0.0
342     0.0
343     0.0
Length: 344, dtype: float64

In [ ]:
# Sort the `percent_missing_by_row` series in descending order
# How many of the rows are mostly empty
sorting = percent_missing_by_row.sort_values(ascending=False)
empty_rows = (percent_missing_by_row > 0).sum()
print(sorting)
print(empty_rows)

3      62.5
271    62.5
268    12.5
256    12.5
218    12.5
       ...
13      0.0
14      0.0
15      0.0
336     0.0
337     0.0
Length: 344, dtype: float64
11

In [ ]:
# Return shape before removing null values
penguins.shape

(344, 8)

In [ ]:
# removing null values. Inplace=True makes this change permamnet
penguins.dropna(axis=0,inplace=True)
penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,year
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,male,2007
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,female,2007
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,female,2007
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,female,2007
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,male,2007
...,...,...,...,...,...,...,...,...
339,Chinstrap,Dream,55.8,19.8,207.0,4000.0,male,2009
340,Chinstrap,Dream,43.5,18.1,202.0,3400.0,female,2009
341,Chinstrap,Dream,49.6,18.2,193.0,3775.0,male,2009
342,Chinstrap,Dream,50.8,19.0,210.0,4100.0,male,2009
343,Chinstrap,Dream,50.2,18.7,198.0,3775.0,female,2009

In [ ]:
# Return shape after removing null values
penguins.shape

(333, 8)